name: Pull Request

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Install Dependencies
      run: |
        pod install
    - name: Build Generate
      run: |
        echo "Archive the iOS app"
        cd $(Build.SourcesDirectory)
        xcodebuild -sdk iphoneos -configuration Release -workspace cicdexample.xcworkspace -scheme cicdexample archive CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY="$(APPLE_CERTIFICATE_SIGNING_IDENTITY)" APP_PROFILE=$(APP_PROFILE_CUG) EXT_PROFILE=$(EXT_PROFILE_CUG) -archivePath mobileApp.xcarchive