name: iOS starter workflow

on:
  workflow_dispatch:
    inputs:
      configuration_name:
        description: "The type of build to generate"
        type: choice
        required: true
        options:
          - "Release"
          - "Debug"
      env_name:
        description: "The type of Env build to generate"
        type: choice
        required: true
        options:
          - "Visapay"
          - "Visapay(DEV)"
          - "Visapay(UAT)"
          - "Visapay(CUG)"

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Default Scheme
        run: |
          echo "Jones ${{ inputs.configuration_name }} ${{ inputs.env_name }}"
